### ISSUE TITLE
Add loops

### ISSUE THREAD

**Issue by BookOwl** [BookOwl/haumea#1]
Shouldn't be too hard.

**Comment by BookOwl** [comment]
PR #7 adds this, but I'm leaving this open to remind me to document them.

**Comment by nanalan** [comment]
Regarding #4, Arrays could use `for..of` loops:

```
myarray = [1, 2, 3, 4]
for value of myarray do
  print value ? idk what the syntax is
end
```

**Comment by BookOwl** [comment]
That's the plan. Once I add Arrays, I'll make `... to ... by ...` an expression that returns an Array.

**Comment by BookOwl** [comment]
I documented the loops in the wiki, so I'm closing this.
