### ISSUE TITLE
Invalid C is generated if a procedure body isn't a block

### ISSUE THREAD

**Issue by Jonathan50** [BookOwl/haumea#12]
```haumea
to test return 1
```
outputs this:
```c
long test() return 1l;
```
There should be braces around the C procedure's body.

**Comment by BookOwl** [comment]
Oops. I'm a C n00b. :P

**Comment by Jonathan50** [comment]
Easy fix: make `compile_function` output braces. It'll make output look a bit strange for procedure bodies that are blocks, though&hellip;

Not really related, but
```haumea
to square with (n) return n * n
```
fails to parse, it outputs this:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/libcollections/vec.rs:1265
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jupiterio** [comment]
@Jonathan50 Maybe make it so it also knows whether the function did or didn't have a block, and output braces accordingly.
